% Auto-generated MATLAB constants file
% Contains paths to installed applications
% Generated by Application Manager

function paths = app_paths()
    % Application paths structure
    paths = struct();

    % InVesalius not found
    paths.invesalius = '';

    % 3D Slicer not found
    paths.slicer = '';

end
